### ISSUE TITLE
Pod doesn't build when using CocoaPods 0.36.0 beta

### ISSUE THREAD

**Issue by SpacyRicochet** [bitstadium/HockeySDK-iOS#129]
The HockeySDK pod doesn't build properly after installing through the new CocoaPods 0.36.0 beta. According to the (Pod Authors Guide to CocoaPods Frameworks)[http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/], the HockeySDK should be updated to accommodate this future version of CocoaPods properly.

![screen shot 2015-02-09 at 15 24 10](https://cloud.githubusercontent.com/assets/904596/6108030/0f15523c-b070-11e4-85f9-4784f702e105.png)

I made a test project that shows the project not building due to being unable to build the `Objective-C module 'HockeySDK'`, because `'CrashReporter/PLCrashReport.h' file not found`.

To check if the beta works at all, I first installed the Alamofire pod to check, but that builds fine. I also tried adding a Bridging Header, but that fails with the same error. To check out a test project illustrating this, you can check out https://github.com/SpacyRicochet/HockeySDKTest.

**Comment by anlinde** [comment]
The SDK build has not yet been tested or updated to support CocoaPods 0.36.0 Beta. This is on our todo-list.

**Comment by rromanchuk** [comment]
Can you guys please move away from binary distributions and officially maintain and support a podspec? It's 2015 :kiss:   Also, your official integration HockeyApp.app client offers a cocoapod installation option, so most swift users are going to run into @SpacyRicochet issue since most of us are running 0.36

**Comment by anlinde** [comment]
@rromanchuk please find some notes attached:

1. CocoaPods 0.36 is in Beta and has known issues that cause our SDK not to build properly, e.g. see here: https://github.com/CocoaPods/CocoaPods/issues/3082 (this is closed but there is no updated CocoaPods release with this included available).
2. Our recommended distribution is binary, because that always works no matter what your build settings are.
3. Our podspec is just fine and officially maintained since 2011.
4. The develop branch has been updated to consider changes CocoaPods 0.36 will require. Since it is not final, it doesn't make sense to update the SDK yet. Feel free to point your Podfile to the develop branch.

**Comment by rromanchuk** [comment]
@anlinde Just bad timing i guess. Started a new swift project today with 5 pods, and the build failed because of hockeyapp. 

Maybe it just *feels* like you don't support the spec because of no official mention of `pod 'HockeySDK'` anywhere except during the HockeyApp.app installation flow.

**Comment by yonaskolb** [comment]
Has anyone found a workaround for this?

**Comment by anlinde** [comment]
When using the release candidate of CocoaPods 0.36 it builds just fine over here.

**Comment by yonaskolb** [comment]
Still doesn't work in the full release of cocoapods 0.36. It builds fine when loaded as a static library, but doesn't allow any swift pods to be integrated as this requires `use_frameworks!` which turns every pod into a framework. Building as a framework fails due to not finding CrashReporter.

If I add `HockeySDK/Vendor` to the header search path (which cocoapods is not adding when building as framework) it finds the CrashReporter headers but then XCode complains about "Include of a non-modular header inside framework module"

@anlinde When you say it works, are you using `use_frameworks!` in your podfile?

**Comment by anlinde** [comment]
Yes, using `use_frameworks!` in the Podfile in my sample project works just fine. Could you please create a sample app and try to reproduce the issue so we can check it ourselves?

**Comment by yonaskolb** [comment]
Ok well these are the steps I followed for my sample app, which I've now repeated to double check
- created a new iOS project in Xcode 6.3 beta 3
- added a podfile with:
```
use_frameworks!
pod 'HockeySDK'
````
- `pod install` in terminal (cocoapods 0.36 full release)
- added `import HockeySDK` to AppDelegate which doesn't compile and says "Could not build objective-C module 'HockeySDK'
- clean and build  - fails with above error and also `CrashReporter/PLCrashReporter.h file not found` in `BITCrashReportTextFormatter.h`

**Comment by wlisac** [comment]
I'm having the same issue. I've tried `master` and `develop`.

**Comment by anlinde** [comment]
Thanks. I just fixed this in the develop branch.

Please use the following line in your Podfile for now to get the fixes until we release a new version:

    pod 'HockeySDK', :git => 'https://github.com/bitstadium/HockeySDK-iOS.git', :branch => 'develop'

**Comment by Sajjon** [comment]
@anlinde I just tried your specified pod settings, it does not work.

I still get " 'CrashReporter/PLCrashReport.h' file not found", on line 37 in file 'BITCrashReportTextFormatter.h'

I get this error either by:
* "#import <HockeySDK/HockeySDK.h>" in "MyApp-Bridging-Header.h" file
or
* "import HockeySDK" in "AppDelegate.swift"

I use Cocoapods 0.36.0 and Swift (Obviously) and 8.1 as deployment target.

What to do? :)

**Comment by anlinde** [comment]
1. You don't need to use the bridging header for this.
2. Did you make sure the Pod was actually updated and the code used by CoocaPods includes the changes from this commit? https://github.com/bitstadium/HockeySDK-iOS/commit/7cc280f45acacddd1f5062537e37f2a387485f7b

**Comment by Sajjon** [comment]
@anlinde OMG how embarrassing, you are 100% right, it works perfectly - thanks a lot!
(never have two different Xcode projects using cocoapods and almost the exact same pods open at the same time in the terminal :P I was performing pod install on the wrong project. )

**Comment by kambala-decapitator** [comment]
thanks @anlinde !

**Comment by tapi** [comment]
Was having this issue and your fix worked for me @anlinde

**Comment by anlinde** [comment]
The latest release 3.6.4 contains the fix for this.
